---
version: '3.8'

services:
 db:
  image: "mysql:5"
  environment:
   MYSQL_ROOT_PASSWORD: shamsheer

 wordpress:
  image: wordpress
  ports:
   - "8989:80"
  deploy:
   replicas: 3
...
